### PR TITLE
Remove SMIL from shape animations

### PR DESCRIPTION
**Pull request by Owen-Delisle**

### CODE REVIEW

**Comment by jbeenie** [comment]
What properties is this PR for? Can you write a comment with the list of properties you are fixing in this PR?

**Comment by Owen-Delisle** [comment]
https://flow97.monday.com/boards/430136636/pulses/586030973

**Comment by Owen-Delisle** [comment]
Remove SMIL injection from loadSVGShapeAnimations() function. TICKET

**Comment by Owen-Delisle** [comment]
[SafariTests.zip](https://github.com/SlantDesign/FlowTemplates/files/4719829/SafariTests.zip)

**Comment by jbeenie** [comment]
Do we still need this function:
image

**Comment by jbeenie** [comment]
Indentation looks off in couple of places:
https://files.slack.com/files-pri/T024GRLDF-F014P3UMY0M/image.png

**Comment by Owen-Delisle** [comment]
[Contraction.zip](https://github.com/SlantDesign/FlowTemplates/files/4720159/Contraction.zip)

**Pull request merged**
